language: java
jdk:
    - oraclejdk8
script:
    - mvn test -B -Pjacoco
after_script:
    - env
    - "[[ $TRAVIS_PULL_REQUEST == false ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}"
